# Generated by Django 4.2 on 2023-04-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test", old_name="test", new_name="snake_value",
        ),
    ]
